title: Clement Osei
logo: co_logo.jpg
description: Data Analyst with expertise in Microsoft Excel, SQL and Power BI, transforming complex data into meaningful insights through data analysis and business intelligence.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
