title: Clement Osei
logo: Clement_Osei_Logo.jpg
description: Data Analyst with expertise in Microsoft Excel, SQL, and Power BI, transforming complex data into meaningful insights through data analysis, interactive dashboards and business intelligence solutions that support strategic decision-making and drive organisational performance.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
